<a href="https://colab.research.google.com/github/ananya-codes-data/Learning-Python/blob/main/Guided_projects/Marketing_campaign_data_cleaning/marketing_campaign_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [10]:
# Load the messy data

df = pd.read_csv('https://raw.githubusercontent.com/ananya-codes-data/Learning-Python/refs/heads/main/Guided_projects/Marketing_campaign_data_cleaning/marketing_campaign_data_messy.csv')

print(f"Loaded Dataset : {df.shape[0]} rows, {df.shape[1]} columns")

Loaded Dataset : 2020 rows, 12 columns

In [11]:
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,TikTok,30592,586,$503.95,77.0,1,NaN,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,NaN,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,Instagram,33254,1117,883.82,214.0,0,NaN,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,Facebook,68728,2960,4198.5,591.0,Yes,NaN,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,Email,96402,1090,1315.59,66.0,Y,NaN,EM

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Campaign_ID   2020 non-null   object
 1   Campaign_Name  2020 non-null   object
 2   Start_Date     2020 non-null   object
 3   End_Date       2020 non-null   object
 4   Channel        1919 non-null   object
 5   Impressions    2020 non-null   int64
 6   Clicks         2020 non-null   int64
 7   Spend          2020 non-null   object
 8   Conversions    1820 non-null   float64
 9   Active         2020 non-null   object
 10  Clicks         40 non-null     float64
 11  Campaign_Tag   2020 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 189.5+ KB

In [ ]:
df.isnull().sum()

 Campaign_ID        0
Campaign_Name       0
Start_Date          0
End_Date            0
Channel           101
Impressions         0
Clicks              0
Spend               0
Conversions       200
Active              0
Clicks           1980
Campaign_Tag        0
dtype: int64

In [13]:
# STEP 1: HEADER CLEANING

print(df.columns.tolist())

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

print("FIX APPLIED")
print(df.columns.tolist())

[' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel', 'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks', 'Campaign_Tag']
FIX APPLIED
['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel', 'impressions', 'clicks', 'spend', 'conversions', 'active', 'clicks', 'campaign_tag']

In [20]:
# STEP 2: TYPE CONVERSION & CURRENCY CLEANING

dirty_spend_mask = df['spend'].astype(str).str.contains(r'\$')
print(df.loc[dirty_spend_mask, ['campaign_id', 'spend']])

df['spend'] = df['spend'].astype(str).str.replace(r'[^\d.-]', '', regex= True)
df['spend'] = pd.to_numeric(df['spend'])

print('FIX APPLIED')
print(df.loc[dirty_spend_mask, ['campaign_id', 'spend']])

     campaign_id     spend
0      CMP-00001   $102.82
21     CMP-00022   $2428.4
22     CMP-00023  $4726.22
31     CMP-00032  $2759.35
32     CMP-00033  $2393.02
...          ...       ...
1992   CMP-01993   $755.86
2002   CMP-01426  $2640.72
2011   CMP-01028  $2422.76
2013   CMP-00388  $2135.23
2015   CMP-00400   $503.95

[298 rows x 2 columns]
FIX APPLIED
     campaign_id    spend
0      CMP-00001   102.82
21     CMP-00022  2428.40
22     CMP-00023  4726.22
31     CMP-00032  2759.35
32     CMP-00033  2393.02
...          ...      ...
1992   CMP-01993   755.86
2002   CMP-01426  2640.72
2011   CMP-01028  2422.76
2013   CMP-00388  2135.23
2015   CMP-00400   503.95

[298 rows x 2 columns]

/tmp/ipykernel_566/539543024.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spend'] = df['spend'].astype(str).str.replace(r'[^\d.-]', '', regex= True)
/tmp/ipykernel_566/539543024.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['spend'] = pd.to_numeric(df['spend'])

In [9]:
# STEP 3: CATEGORICAL TYPOS (FUZZY LOGIC)

print(df['channel'].unique())

cleanup_map = {
    'Facebok': 'Facebook',
    'Tik_Tok': 'TikTok',
    'E-mail': 'Email',
    'Insta_gram': 'Instagram',
    'Gogle': 'Google Ads',
    'N/A': np.nan   # Handling the ghost value here too
}

df['channel'] = df['channel'].replace(cleanup_map)

print("FIX APPLIED")
print(df['channel'].unique())

['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' 'E-mail' nan 'Gogle'
 'Tik_Tok' 'Facebok' 'Insta_gram']
FIX APPLIED
['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' nan]

In [11]:
# STEP 4: HANDLING MIXED BOOLEANS

print(df['active'].unique())

bool_map = {
    'Yes': True,
    'Y': True,
    '1': True,
    1: True,
    'No': False,
    '0': False,
    0: False
}

df['active'] = df['active'].map(bool_map).fillna(False).astype(bool)

print("FIX APPLIED")
print(df['active'].unique())

['Y' '0' 'No' 'True' 'Yes' '1' 'False']
FIX APPLIED
[ True False]

/tmp/ipykernel_776/53451654.py:15: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['active'] = df['active'].map(bool_map).fillna(False).astype(bool)

In [14]:
# STEP 5: DATE PARSING

print(df['start_date'].dtype)
print(df['end_date'].dtype)

df['start_date'] = pd.to_datetime(df['start_date'], errors= 'coerce')
df['end_date'] = pd.to_datetime(df['end_date'], dayfirst= True, errors= 'coerce')

print("FIX APPLIED")

print(df['start_date'].dtype)
print(df['end_date'].dtype)

object
object
FIX APPLIED
datetime64[ns]
datetime64[ns]

/tmp/ipykernel_566/771143521.py:7: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['end_date'] = pd.to_datetime(df['end_date'], dayfirst= True, errors= 'coerce')

In [30]:
df = df.loc[:, ~df.columns.duplicated()]
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,-5315.1575,20.0,Y,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,-5315.1575,1.0,0,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,-5315.1575,51.0,No,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,-5315.1575,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,-5315.1575,30.0,Yes,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,-5315.1575,77.0,1,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,-5315.1575,162.0,0,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,-5315.1575,214.0,0,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,-5315.1575,591.0,Yes,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,-5315.1575,66.0,Y,EM

In [17]:
# STEP 6: LOGICAL INTEGRITY (CLICKS vs IMPRESSIONS)

impossible_mask = df['clicks'] > df['impressions']
print(df.loc[impossible_mask, ['campaign_id', 'impressions', 'clicks']])

Empty DataFrame
Columns: [campaign_id, impressions, clicks]
Index: []

In [18]:
# STEP 7: LOGICAL INTEGRITY (TIME TRAVEL)

time_travel_mask = df['start_date'] > df['end_date']
print(df.loc[time_travel_mask, ['campaign_id', 'start_date', 'end_date']].head(5))

# assuming that campaign last for 30 days

df.loc[time_travel_mask, 'end_date'] = df.loc[time_travel_mask, 'start_date'] + pd.Timedelta(days = 30)

print("FIX APPLIED")

print(df.loc[time_travel_mask, ['campaign_id', 'start_date', 'end_date']].head(5))

    campaign_id start_date   end_date
23    CMP-00024 2023-05-06 2023-05-01
54    CMP-00055 2023-09-01 2023-08-27
71    CMP-00072 2023-02-01 2023-01-27
156   CMP-00157 2023-12-06 2023-12-01
200   CMP-00201 2023-01-11 2023-01-06
FIX APPLIED
    campaign_id start_date   end_date
23    CMP-00024 2023-05-06 2023-06-05
54    CMP-00055 2023-09-01 2023-10-01
71    CMP-00072 2023-02-01 2023-03-03
156   CMP-00157 2023-12-06 2024-01-05
200   CMP-00201 2023-01-11 2023-02-10

In [31]:
# STEP 8: HANDLING OUTLIERS (WINSORIZING) #### error -- need to fix this code

Q1 = df['spend'].quantile(0.25)
Q3 = df['spend'].quantile(0.75)

IQR = Q3 - Q1

upper_limit = Q3 + (3 * IQR)
print("upper limit =", upper_limit)
upper_outlier_mask = df['spend'] > upper_limit
print(df.loc[upper_outlier_mask, ['campaign_id', 'spend']].head(2))

print("FIX APPLIED")
df.loc[upper_outlier_mask, 'spend'] = upper_limit
print(df.loc[upper_outlier_mask, ['campaign_id', 'spend']].head(2))


lower_limit = Q1 - (3 * IQR)
print("lower limit =", lower_limit)
lower_outlier_mask = df['spend'] > lower_limit
print(df.loc[lower_outlier_mask, ['campaign_id', 'spend']].head(2))

print("FIX APPLIED")
df.loc[lower_outlier_mask, 'spend'] = lower_limit
print(df.loc[lower_outlier_mask, ['campaign_id', 'spend']].head(2))

upper limit = -5315.157499999999
Empty DataFrame
Columns: [campaign_id, spend]
Index: []
FIX APPLIED
Empty DataFrame
Columns: [campaign_id, spend]
Index: []
lower limit = -5315.157499999999
Empty DataFrame
Columns: [campaign_id, spend]
Index: []
FIX APPLIED
Empty DataFrame
Columns: [campaign_id, spend]
Index: []

In [ ]:
# STEP 9: STRING PARSING (FEATURE EXTRACTION)